- name: Install brew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
  with_items:
    - { name: clipy }
    - { name: docker }
    - { name: drawio }
    - { name: google-chrome }
    - { name: resilio-sync }
    - { name: spotify }
    - { name: typora }
    - { name: dynalist }

- name: Tap brew packages
  homebrew_tap:
    name: "homebrew/cask-fonts"
- name: Install font
  homebrew_cask:
    name: font-fira-code-nerd-font

- name: Install mas which is package manager of Mac App Store
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: mas }
